### ISSUE TITLE
Version 0.2.0 from crates.io cannot be built

### ISSUE THREAD

**Issue by lennartS** [Ogeon/rust-wiringpi#11]
I always get a build error when I use version 0.2.0 of `rust-wiringpi`from crates.io as dependency.

## Steps to reproduce
* Create a new binary project: `cargo new --bin reproduce-wiringpi-build; cd reproduce-wiringpi-build`
* Add `rust-wiringpi` dependency version 0.2.0 from crates.io: `echo 'wiringpi = "0.2.0"' >> Cargo.toml`
* Build the project: `cargo build`

## Expected behaviour
The project is built as normal and you get a Hello World executable that depends on `rust-wiringpi`.

## Actual behaviour
The build fails with the following error message:
~~~
   Compiling wiringpi v0.2.0
error: failed to run custom build command for `wiringpi v0.2.0`
process didn't exit successfully: `/home/pi/devel/reproduce-wiringpi-build/target/debug/build/wiringpi-0a1dc846a0a619d0/build-script-build` (exit code: 101)
--- stdout
make -C wiringPi/wiringPi clean
Makefile:3: recipe for target 'wiringpi' failed

--- stderr

make[1]: *** wiringPi/wiringPi: No such file or directory.  Stop.
make: *** [wiringpi] Error 2
thread 'main' panicked at 'failed to build wiringPi C library (exit code Some(2))', /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/wiringpi-0.2.0/build.rs:12
note: Run with `RUST_BACKTRACE=1` for a backtrace.
~~~

## Possible Workaround
To work around this issue you can clone `rust-wiringpi` locally and run `git submodule init; git submodule update` in the created directory. Then you have to use this local dependency in the `Cargo.toml` of your project and it will build just fine.

## Further information
It seems to me that the submodule `wiringPi` is not initialized correctly during the build. I'm not quite sure if it would be a good idea to add a `git submodule init; git submodule update` to the `build.rs` file, as it may overwrite changes done by the user if the `rust-wiringpi` is **not** taken from crates.io.

**Comment by Ogeon** [comment]
Thanks for letting me know! Sounds like it was published without all the
necessary files. I'll investigate and republish.

**Comment by Ogeon** [comment]
Ok, so I republished with version 0.2.1, and reran your reproduction steps. It should work now.

**Comment by lennartS** [comment]
Thanks for the quick response. I can confirm that it works fine with version 0.2.1 from crates.io, so I think the issue can be closed.

**Comment by Ogeon** [comment]
Nice! I'll close it.
