### ISSUE TITLE
Don't force overwrite CC in makefile

### ISSUE THREAD

**Issue by Lindenk** [Ogeon/rust-wiringpi#16]
Hello!

I am currently cross compiling a several libraries for rpi in my project, mostly by defining my own cross compiler in a build script. Unfortunately, rust-wiringpi force overwrites the CC I define as part of the build which causes rust-wiringpi to fail it's build. So, I would like to request CC only be set if it hasn't already been set before hand when building rust-wiringpi.

**Comment by Ogeon** [comment]
Ah, yes, the makefile does that. Do you know of a good way to change it? In that case I'll gladly accept a pull request! Then you may also be able to check beforehand that it works with your setup.

**Comment by Lindenk** [comment]
@Ogeon I submitted a pull request. Basically, if CC is set beforehand, it doesn't set it's own CC. This seems to solve my problem rather nicely.

**Comment by Ogeon** [comment]
Sorry for not responding until now, but I have been spending my time with
family during the past week. I should have written something, if only to
acknowledge it, but got carried away by the preparations before Christmas.
:/

I will probably have to wait at least until tomorrow before I can have a
look, though. I want to prioritize family time, while I have the
opportunity!

Either way, thanks for taking the time to make the pull request! It's
always appreciated!

**Comment by Lindenk** [comment]
No worries! I just wanted to make sure you got the a notification at some point (partly because it's my job). There's no need to rush, whenever you have the time to look it over is fine with me.

**Comment by Ogeon** [comment]
I see! I hope it's not a blocker for you. Otherwise you may be able to use
the (uploaded) git branch as a temporary dependency.
