### ISSUE TITLE
Why it's deprecated

### ISSUE THREAD

**Issue by Ogeon** [Ogeon/rust-wiringpi#32]
The creator of the wrapped WiringPi library has chosen to deprecate it. As part of that, he has taken down the Git repository (at the time of writing), so it's practically impossible to make new builds of rust-wiringpi from the real source. Due to that, I'm no longer going to maintain this library.

Gordon himself writes about it on http://wiringpi.com/wiringpi-deprecated/.

Thanks, Gordon, for creating WiringPi, and sorry for being one of those who linked it statically. Also, big thanks to everyone who have contributed to rust-wiringpi.

**Comment by Razican** [comment]
It's sad to see this deprecated :( there is still the GitHub mirror, though: https://github.com/WiringPi/WiringPi

**Comment by Ogeon** [comment]
Good point. I hadn't seen it. I suppose it can be used for reproducing the builds, but other than that I believe there are (or can be) better alternatives for Rust. WiringPi is a bit too C focused for a smooth integration.
