### ISSUE TITLE
Add bindings for SPI functions (<wiringPiSPI.h>)

### ISSUE THREAD

**Issue by phip1611** [Ogeon/rust-wiringpi#33]
Are you planning to add bindings for SPI functions (<wiringPiSPI.h>)?
I don't know yet whether this should be a separate crate or not.
Did you think about this yet?

**Comment by phip1611** [comment]
Okay, I didn't see that one: #32

**Comment by Ogeon** [comment]
Yeah, sorry about that. I should archive this repo.
